server:
    #address: 127.0.0.1
    port: 8080
    context-path: /
cxf:
    path: /ws
    servlet:
        init:
            service-list-path: /info
    jaxrs:
        component-scan: false
info:
    app:
        name: Example of JAX-RS
        description: JAXRS 例子程序 .
    contact:
        email: 286999915@qq.com
        wechat: Arc_Qian
spring:
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true